/-
Zeta5/Sec6/Final.lean  —  (6.14) and Proposition 6.3.  `eq_6_14` is proved from the
configuration bound `Sec6.configBound` (`Sec6/Energy.lean`) and the Gram-integral argument
`Sec6.Gram.eq_6_14_of_config` (`Sec6/Gram.lean`).  The statements `Zeta5.RealBound.eq_6_14`
and `Zeta5.RealBound.prop_6_3` are in the namespace of `Zeta5/RealBound.lean`, which proves
(6.15) and the passage (6.14) ⇒ (6.16).  `#print axioms Zeta5.RealBound.eq_6_14` gives
`[propext, Classical.choice, Quot.sound]`.

## The route

```
eq_6_14  ⇐  Gram.eq_6_14_of_config         (6.10)–(6.13)          Gram.lean
         ⇐  configBound ⇐ config_log      (6.9')                 Energy.lean
              ⇐ eq_6_6_cauchy              (6.6')                 Energy.lean
                 ⇐ cauchy_cnd             Lemma 6.2 for kC ε     CND.lean
                     ⇐ frullani_cauchy, frullani_integrable       Frullani.lean
                     ⇐ gauss_pd                                   GaussPD.lean
                     ⇐ swap_frullani                              Swap.lean
                 ⇐ rho_cross              cross term             RhoCross.lean
                     ⇐ arcsine_smooth_err                         SmoothArc.lean
                         ⇐ smooth_err_norm                        SmoothErr.lean
                             ⇐ exists_nearest_cos, cos_sub_cos_ge SmoothAux.lean
                             ⇐ integral_log_one_add_sq_div        Antideriv.lean
                         ⇐ arcsine_pot            (A.1)           ArcsinePot.lean
                             ⇐ integral_log_abs_sub_cos           LogCos.lean
                                 ⇐ intervalIntegrable_log_abs_sub_cos
                                                                  LogCosInt.lean
                                 ⇐ integral_log_abs_sub_cos_of_abs_le
                                                                  LogCosOn.lean
                                 ⇐ integral_log_abs_sub_cos_of_one_lt_abs
                                                                  LogCosOff.lean
                 ⇐ rho_energy_ge          (A.2), energy of ρ     RhoEnergy.lean
                     ⇐ pair_energy_ge  (uses arcsine_pot)         PairEnergy.lean
                     ⇐ kE_arc_comm                                ArcComm.lean
                     ⇐ kE_rhoM_expand                             Bilinear.lean
                     ⇐ Irho_double_sum                            IrhoSum.lean
              ⇐ eq_6_7_field               (6.7) for V of (6.1)   Potential.lean
                 ⇐ Vfield_eq_Vclosed (A.5)                        Field.lean
                     ⇐ integral_log_add_sq                        Field.lean
                 ⇐ Num.eq_6_7_closed       (6.2), (6.7), (6.8)    Num/*.lean
```

All files are in `Zeta5/Sec6/`.  Shared definitions are in `Defs.lean`; elementary facts about
the measures in `Measures.lean`.  `Num/` is the kernel-checked certified partition for
(6.2)/(6.7) (1049 cells on `[0,2]`, 2 on `[2,4]`, an analytic tail for `t ≥ 4`; generated by
`numerics/sec6/gen_lean.py`).

**Deviation from the paper (energy step).**  The paper regularises the configuration by
circles of radius `ε` in `ℂ` and applies Lemma 6.2 to the singular kernel `log|z − w|`.  Here
the points stay Dirac masses and the kernel is regularised instead:
`kC ε x = ½ log(x² + ε²)` (`Sec6/Defs.lean`).  The zero-mass argument of Lemma 6.2 (Gaussian
positive definiteness and a Frullani representation) applies to `kC ε`, which is bounded on
compacts, so the diagonal, the log-integrability hypothesis and the dominated convergence
step of Lemma 6.2 are not needed; every singular integral is one-dimensional (in `θ`, for the
arcsine measures `θ ↦ m + r cos θ`).  (6.9') has `20h` where the paper has `(120+√2)h`, and
`eq_6_14_of_config` accepts `3h log K + 131h`.

**Deviation from the paper (Gram step)**: see `Sec6/Gram.lean`.  The `1/h!` of (6.10) is kept
through to (6.14).  The paper keeps it in (6.13) and discards it (`log h! ≥ 0`) only when it
takes logarithms.  Here it pays for one `h log K`, so `eq_6_14_of_config` accepts
`3h log K + 131h`; `configBound`'s `2h log K + 20h` would not need it.
`∫_0^∞(1+y)⁵e^{-y/K}dy ≤ 326K⁶` replaces the constant `652`.

**Deviation from the paper (potential inequality (6.2)/(6.7))**: Appendix A's route — the
bound `ℬ(l,r)` of (A.9) on the 684 cells of Table 2 — is not used.  `Num/` instead evaluates
the closed forms (A.1)/(A.5) of `2U^ρ − V` directly, with certified interval arithmetic, on
its own partition (1049 cells on `[0,2]`, 2 on `[2,4]`), every cell checked by
`decide +kernel`; `t ≥ 4` is an analytic bound (`Num/Tail.lean`) replacing (6.8).  That
Table 2 tiles `[0,2]` is proved (`RealBound.table2_tiles`) but is not used by `eq_6_14`.

**Deviation from the paper (smoothing error)**: the paper's mass bound and
`∫U^ρ dω_i − U^ρ(t_i) ≤ 60√ε` (p. 19) are replaced by a bound on the Cauchy-kernel smoothing
error against an arcsine measure, `smooth_err_norm` (`π(δ + π√(2δ))`, via the nearest point
of `[−1,1]` in angle form and `∫_0^X log(1+b²/x²)dx`), giving the cross term `rho_cross`
with `88√ε + 420ε`.

**The arcsine potential (A.1)** is proved in normalised form (`LogCos*.lean`): on `[−1,1]` by
the product formula for `cos φ − cos θ` and `∫_0^π log sin = −π log 2`; off `[−1,1]` by
Mathlib's circle average `circleAverage_log_norm_sub_const₂`.  (A.2) is used only as the
lower bound `I(ρ) ≤ I_k(ρ,ρ)` (`rho_energy_ge`), for the kernel `kC ε ≥ log|·|`.
-/
import Zeta5.Sec6.Energy

namespace Zeta5
namespace RealBound

open Real

/-- **(6.14)** (p. 20).  For `K ∈ 40ℤ_{>0}`,

`log Δ_K(ζ(5)) ≤ 2h(h + 6N − K) log K + (λM₀ − I(ρ))K² + 18h log K + 160h`.

Stated as printed, with the hypothesis `0 < Δ_K(ζ(5))`.  Proved from the configuration bound
`Sec6.configBound` (the paper's (6.9) with `20h` in place of `(120+√2)h`) by the Gram-integral
argument `Sec6.Gram.eq_6_14_of_config` ((6.10)–(6.13)), which accepts any configuration
constant `A ≤ (λM₀ − I(ρ))K² + 3h log K + 131h`. -/
theorem eq_6_14 (n : ℕ) (hn : 0 < n) (hΔpos : 0 < evalZeta5 (Delta n)) :
    Real.log (evalZeta5 (Delta n))
      ≤ 2 * (h n : ℝ) * ((h n : ℝ) + 6 * (N n : ℝ) - (K n : ℝ)) * Real.log (K n : ℝ)
        + ((lam : ℝ) * M0 - Irho) * (K n : ℝ) ^ 2
        + 18 * (h n : ℝ) * Real.log (K n : ℝ) + 160 * (h n : ℝ) := by
  refine Sec6.Gram.eq_6_14_of_config n hn hΔpos _ (Sec6.configBound n hn) ?_
  have hn1 : (1 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
  have hK : ((K n : ℕ) : ℝ) = 40 * (n : ℝ) := by simp only [K]; push_cast; ring
  have hlogK : 0 ≤ Real.log (K n : ℝ) := Real.log_nonneg (by rw [hK]; linarith)
  have hh : (0 : ℝ) ≤ (h n : ℝ) := by positivity
  nlinarith [mul_nonneg hh hlogK]

/-- **Proposition 6.3**, (6.16) (p. 20): `log F_K(ζ(5)) ≤ Ū K² + 24K log K + 200K`.

`hΔpos` is the positivity `0 < Δ_K(ζ(5))`, which the paper gets from Proposition 2.2;
in the project it is `Zeta5.delta_pos`, and `Zeta5.prop_6_3` (`Interface.lean`) is
`Zeta5.RealBound.prop_6_3 n hn (Zeta5.delta_pos n)`. -/
theorem prop_6_3 (n : ℕ) (hn : 0 < n) (hΔpos : 0 < evalZeta5 (Delta n)) :
    Real.log (evalZeta5 (F n))
      ≤ (Ubar : ℝ) * (K n : ℝ) ^ 2 + 24 * (K n : ℝ) * Real.log (K n : ℝ)
        + 200 * (K n : ℝ) :=
  prop_6_3_of n hn hΔpos (eq_6_14 n hn hΔpos) (eq_6_15 n hn)

end RealBound
end Zeta5
