"""Generate the certified-partition modules Zeta5/Sec6/Num/Seg*.lean and Num/Final.lean
from the partition points in partition/pts.txt (each point is k * 10^-12).

Run from the repository root:  python3 numerics/sec6/gen_lean.py

The partition itself was produced by partition/gen.py (greedy: widest cell whose bound
clears M0 with 1e-4 to spare, then shrunk by 3%) and partition/gen24.py (the two cells of
[2,4], checked against M0 - 3/10).  Every cell is re-verified by the Lean kernel
(`decide +kernel` on `chainOK`), so nothing here needs to be trusted.

Kernel memory grows by ~40 MB per cell within one declaration, so segments hold at most
35 cells, and the segment modules are arranged in two linear import chains (Seg1 -> Seg2 ->
Seg3, Seg4 -> Seg5 -> Seg6) so that at most two of them are checked at the same time."""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
PTS = list(map(int, open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                      'partition', 'pts.txt')).read().split()))
PTS24 = [2000000000000, 2875904685649, 4000000000000]
CH = 35          # cells per segment theorem
PER_MOD = 5      # segment theorems per module
OUT = os.path.join(ROOT, 'Zeta5', 'Sec6', 'Num')

HEAD = """/-
Zeta5/Sec6/Num/{name}.lean  —  GENERATED by numerics/sec6/gen_lean.py; do not edit.

Kernel-checked cells of the certified partition of `[0,2]` for (6.2): each `segK` checks
at most {ch} consecutive cells `[k_i·10⁻¹², k_(i+1)·10⁻¹²]` with `decide +kernel` on
`chainOK` (see `Num/Cell.lean`, `chain_sound`).
-/
import {imp}

namespace Zeta5
namespace Sec6
namespace Num

open Real

"""
TAIL = """
end Num
end Sec6
end Zeta5
"""


def seg(name, c, M, Mtxt):
    a, b, rest = c[0], c[1], c[2:]
    return f"""theorem {name} (t : ℝ) (h1 : ({a} : ℝ) / 10 ^ 12 ≤ t) (h2 : t ≤ ({c[-1]} : ℝ) / 10 ^ 12) :
    2 * Uclosed t - Vclosed t ≤ {Mtxt} := by
  have h := chain_sound ({M}) {rest} {a} {b} (by decide +kernel) t (by exact_mod_cast h1)
    (by simpa using h2)
  push_cast at h; linarith
"""


segs = []
i = 0
while i < len(PTS) - 1:
    c = PTS[i:i + CH + 1]
    segs.append(c)
    i += CH
nseg = len(segs)
assert nseg == 30, nseg
mods = []
for mi in range(0, nseg, PER_MOD):
    mods.append(list(range(mi, min(nseg, mi + PER_MOD))))
# two chains: Seg1->Seg2->Seg3, Seg4->Seg5->Seg6
names = [f"Seg{k + 1}" for k in range(len(mods))]
half = len(mods) // 2
for k, idxs in enumerate(mods):
    if k == 0 or k == half:
        imp = "Zeta5.Sec6.Num.Cell"
    else:
        imp = f"Zeta5.Sec6.Num.{names[k - 1]}"
    body = HEAD.format(name=names[k], ch=CH, imp=imp)
    for j in idxs:
        body += seg(f"seg{j}", segs[j], "-1329/200", "-1329 / 200") + "\n"
    body += TAIL
    open(os.path.join(OUT, names[k] + ".lean"), "w").write(body)

# Final: the [2,4] cells, the glue, (6.2) and (6.7) for the closed forms.
fin = """/-
Zeta5/Sec6/Num/Final.lean  —  GENERATED by numerics/sec6/gen_lean.py; do not edit.

**(6.2) and (6.7) for the closed forms** (A.1)/(A.5), on the whole half-line:
`2U^ρ(t) − V(t) ≤ M₀` (`eq_6_2_closed`) and `2U^ρ(t) − V(t) + √t/K ≤ M₀ + √2/K` for `K ≥ 2`
(`eq_6_7_closed`).  `[0,2]` is covered by the 1049 kernel-checked cells of `Seg1`–`Seg6`
(the formalisation's own partition, not Table 2), `[2,4]` by the two cells of `segB`
(against `M₀ − 3/10`), and `t ≥ 4` by the analytic bound `tail_bound_ge4` (`Num/Tail.lean`),
which replaces (6.8).
-/
import Zeta5.Sec6.Num.{last1}
import Zeta5.Sec6.Num.{last2}
import Zeta5.Sec6.Num.Tail

namespace Zeta5
namespace Sec6
namespace Num

open Real

""".format(last1=names[half - 1], last2=names[-1])
fin += seg("segB", PTS24, "-1389/200", "-1389 / 200") + "\n"
g = ["theorem pot_on_02 (t : ℝ) (h0 : 0 ≤ t) (h2 : t ≤ 2) :",
     "    2 * Uclosed t - Vclosed t ≤ -1329 / 200 := by"]
for j, c in enumerate(segs[:-1]):
    b = c[-1]
    g.append(f"  by_cases c{j} : t ≤ ({b} : ℝ) / 10 ^ 12")
    lo = "(by norm_num; linarith)" if j == 0 else "(by linarith)"
    g.append(f"  · exact seg{j} t {lo} c{j}")
    g.append(f"  push Not at c{j}")
j = nseg - 1
g.append(f"  exact seg{j} t (by linarith) (by norm_num; linarith)")
fin += "\n".join(g) + "\n"
fin += """
theorem pot_on_24 (t : ℝ) (h0 : 2 ≤ t) (h2 : t ≤ 4) :
    2 * Uclosed t - Vclosed t ≤ -1389 / 200 :=
  segB t (by norm_num; linarith) (by norm_num; linarith)

/-- **(6.2)** for the closed forms (A.1)/(A.5): `2U^ρ(t) - V(t) ≤ M₀` for all `t ≥ 0`. -/
theorem eq_6_2_closed (t : ℝ) (ht : 0 ≤ t) : 2 * Uclosed t - Vclosed t ≤ -1329 / 200 := by
  rcases le_or_gt t 2 with h | h
  · exact pot_on_02 t ht h
  rcases le_or_gt t 4 with h' | h'
  · linarith [pot_on_24 t h.le h']
  · have := tail_bound_ge4 (K := 2) h'.le le_rfl
    linarith [Real.sqrt_nonneg t]

/-- **(6.7)** for the closed forms: `2U^ρ(t) - V(t) + √t/K ≤ M₀ + √2/K` (`K ≥ 2`, `t ≥ 0`). -/
theorem eq_6_7_closed (K : ℝ) (hK : 2 ≤ K) (t : ℝ) (ht : 0 ≤ t) :
    2 * Uclosed t - Vclosed t + Real.sqrt t / K ≤ -1329 / 200 + Real.sqrt 2 / K := by
  have hK0 : 0 < K := by linarith
  have hs2 : 0 ≤ Real.sqrt 2 / K := by positivity
  rcases le_or_gt t 2 with h | h
  · have := eq_6_2_closed t ht
    have : Real.sqrt t / K ≤ Real.sqrt 2 / K :=
      div_le_div_of_nonneg_right (Real.sqrt_le_sqrt h) hK0.le
    linarith
  rcases le_or_gt t 4 with h' | h'
  · have hp := pot_on_24 t h.le h'
    have hst : Real.sqrt t ≤ 2 := by
      rw [show (2 : ℝ) = Real.sqrt (2 ^ 2) by rw [Real.sqrt_sq (by norm_num)]]
      exact Real.sqrt_le_sqrt (by linarith)
    have hsq2 : (7 / 5 : ℝ) ≤ Real.sqrt 2 := by
      rw [show (7 / 5 : ℝ) = Real.sqrt ((7 / 5) ^ 2) by rw [Real.sqrt_sq (by norm_num)]]
      exact Real.sqrt_le_sqrt (by norm_num)
    have hd : (Real.sqrt t - Real.sqrt 2) / K ≤ 3 / 10 := by
      rw [div_le_iff₀ hK0]; nlinarith
    have : Real.sqrt t / K - Real.sqrt 2 / K = (Real.sqrt t - Real.sqrt 2) / K := by ring
    linarith
  · linarith [tail_bound_ge4 h'.le hK]
"""
fin += TAIL
open(os.path.join(OUT, "Final.lean"), "w").write(fin)
print(nseg, "segments in", len(mods), "modules:", names)
