/-
Zeta5/Sec6/Num/Final.lean  —  GENERATED by numerics/sec6/gen_lean.py; do not edit.

**(6.2) and (6.7) for the closed forms** (A.1)/(A.5), on the whole half-line:
`2U^ρ(t) − V(t) ≤ M₀` (`eq_6_2_closed`) and `2U^ρ(t) − V(t) + √t/K ≤ M₀ + √2/K` for `K ≥ 2`
(`eq_6_7_closed`).  `[0,2]` is covered by the 1049 kernel-checked cells of `Seg1`–`Seg6`
(the formalisation's own partition, not Table 2), `[2,4]` by the two cells of `segB`
(against `M₀ − 3/10`), and `t ≥ 4` by the analytic bound `tail_bound_ge4` (`Num/Tail.lean`),
which replaces (6.8).  THIS FILE CONTAINS NO `sorry`.
-/
import Zeta5.Sec6.Num.Seg3
import Zeta5.Sec6.Num.Seg6
import Zeta5.Sec6.Num.Tail

namespace Zeta5
namespace Sec6
namespace Num

open Real

theorem segB (t : ℝ) (h1 : (2000000000000 : ℝ) / 10 ^ 12 ≤ t) (h2 : t ≤ (4000000000000 : ℝ) / 10 ^ 12) :
    2 * Uclosed t - Vclosed t ≤ -1389 / 200 := by
  have h := chain_sound (-1389/200) [4000000000000] 2000000000000 2875904685649 (by decide +kernel) t (by exact_mod_cast h1)
    (by simpa using h2)
  push_cast at h; linarith

theorem pot_on_02 (t : ℝ) (h0 : 0 ≤ t) (h2 : t ≤ 2) :
    2 * Uclosed t - Vclosed t ≤ -1329 / 200 := by
  by_cases c0 : t ≤ (578197906 : ℝ) / 10 ^ 12
  · exact seg0 t (by norm_num; linarith) c0
  push Not at c0
  by_cases c1 : t ≤ (2054872892 : ℝ) / 10 ^ 12
  · exact seg1 t (by linarith) c1
  push Not at c1
  by_cases c2 : t ≤ (4006696477 : ℝ) / 10 ^ 12
  · exact seg2 t (by linarith) c2
  push Not at c2
  by_cases c3 : t ≤ (6089563614 : ℝ) / 10 ^ 12
  · exact seg3 t (by linarith) c3
  push Not at c3
  by_cases c4 : t ≤ (9226360661 : ℝ) / 10 ^ 12
  · exact seg4 t (by linarith) c4
  push Not at c4
  by_cases c5 : t ≤ (12333610898 : ℝ) / 10 ^ 12
  · exact seg5 t (by linarith) c5
  push Not at c5
  by_cases c6 : t ≤ (18391132848 : ℝ) / 10 ^ 12
  · exact seg6 t (by linarith) c6
  push Not at c6
  by_cases c7 : t ≤ (28109968242 : ℝ) / 10 ^ 12
  · exact seg7 t (by linarith) c7
  push Not at c7
  by_cases c8 : t ≤ (34362762418 : ℝ) / 10 ^ 12
  · exact seg8 t (by linarith) c8
  push Not at c8
  by_cases c9 : t ≤ (48681934918 : ℝ) / 10 ^ 12
  · exact seg9 t (by linarith) c9
  push Not at c9
  by_cases c10 : t ≤ (69593409603 : ℝ) / 10 ^ 12
  · exact seg10 t (by linarith) c10
  push Not at c10
  by_cases c11 : t ≤ (79058748580 : ℝ) / 10 ^ 12
  · exact seg11 t (by linarith) c11
  push Not at c11
  by_cases c12 : t ≤ (109561080471 : ℝ) / 10 ^ 12
  · exact seg12 t (by linarith) c12
  push Not at c12
  by_cases c13 : t ≤ (124824805924 : ℝ) / 10 ^ 12
  · exact seg13 t (by linarith) c13
  push Not at c13
  by_cases c14 : t ≤ (160381854792 : ℝ) / 10 ^ 12
  · exact seg14 t (by linarith) c14
  push Not at c14
  by_cases c15 : t ≤ (194774987542 : ℝ) / 10 ^ 12
  · exact seg15 t (by linarith) c15
  push Not at c15
  by_cases c16 : t ≤ (223670476197 : ℝ) / 10 ^ 12
  · exact seg16 t (by linarith) c16
  push Not at c16
  by_cases c17 : t ≤ (277321086594 : ℝ) / 10 ^ 12
  · exact seg17 t (by linarith) c17
  push Not at c17
  by_cases c18 : t ≤ (299133002720 : ℝ) / 10 ^ 12
  · exact seg18 t (by linarith) c18
  push Not at c18
  by_cases c19 : t ≤ (361428782994 : ℝ) / 10 ^ 12
  · exact seg19 t (by linarith) c19
  push Not at c19
  by_cases c20 : t ≤ (383987255507 : ℝ) / 10 ^ 12
  · exact seg20 t (by linarith) c20
  push Not at c20
  by_cases c21 : t ≤ (449952288191 : ℝ) / 10 ^ 12
  · exact seg21 t (by linarith) c21
  push Not at c21
  by_cases c22 : t ≤ (477914368223 : ℝ) / 10 ^ 12
  · exact seg22 t (by linarith) c22
  push Not at c22
  by_cases c23 : t ≤ (539884840887 : ℝ) / 10 ^ 12
  · exact seg23 t (by linarith) c23
  push Not at c23
  by_cases c24 : t ≤ (583506646091 : ℝ) / 10 ^ 12
  · exact seg24 t (by linarith) c24
  push Not at c24
  by_cases c25 : t ≤ (626687466406 : ℝ) / 10 ^ 12
  · exact seg25 t (by linarith) c25
  push Not at c25
  by_cases c26 : t ≤ (677762665531 : ℝ) / 10 ^ 12
  · exact seg26 t (by linarith) c26
  push Not at c26
  by_cases c27 : t ≤ (717697299570 : ℝ) / 10 ^ 12
  · exact seg27 t (by linarith) c27
  push Not at c27
  by_cases c28 : t ≤ (752927442473 : ℝ) / 10 ^ 12
  · exact seg28 t (by linarith) c28
  push Not at c28
  exact seg29 t (by linarith) (by norm_num; linarith)

theorem pot_on_24 (t : ℝ) (h0 : 2 ≤ t) (h2 : t ≤ 4) :
    2 * Uclosed t - Vclosed t ≤ -1389 / 200 :=
  segB t (by norm_num; linarith) (by norm_num; linarith)

/-- **(6.2)** for the closed forms (A.1)/(A.5): `2U^ρ(t) - V(t) ≤ M₀` for all `t ≥ 0`. -/
theorem eq_6_2_closed (t : ℝ) (ht : 0 ≤ t) : 2 * Uclosed t - Vclosed t ≤ -1329 / 200 := by
  rcases le_or_gt t 2 with h | h
  · exact pot_on_02 t ht h
  rcases le_or_gt t 4 with h' | h'
  · linarith [pot_on_24 t h.le h']
  · have := tail_bound_ge4 (K := 2) h'.le le_rfl
    linarith [Real.sqrt_nonneg t]

/-- **(6.7)** for the closed forms: `2U^ρ(t) - V(t) + √t/K ≤ M₀ + √2/K` (`K ≥ 2`, `t ≥ 0`). -/
theorem eq_6_7_closed (K : ℝ) (hK : 2 ≤ K) (t : ℝ) (ht : 0 ≤ t) :
    2 * Uclosed t - Vclosed t + Real.sqrt t / K ≤ -1329 / 200 + Real.sqrt 2 / K := by
  have hK0 : 0 < K := by linarith
  have hs2 : 0 ≤ Real.sqrt 2 / K := by positivity
  rcases le_or_gt t 2 with h | h
  · have := eq_6_2_closed t ht
    have : Real.sqrt t / K ≤ Real.sqrt 2 / K :=
      div_le_div_of_nonneg_right (Real.sqrt_le_sqrt h) hK0.le
    linarith
  rcases le_or_gt t 4 with h' | h'
  · have hp := pot_on_24 t h.le h'
    have hst : Real.sqrt t ≤ 2 := by
      rw [show (2 : ℝ) = Real.sqrt (2 ^ 2) by rw [Real.sqrt_sq (by norm_num)]]
      exact Real.sqrt_le_sqrt (by linarith)
    have hsq2 : (7 / 5 : ℝ) ≤ Real.sqrt 2 := by
      rw [show (7 / 5 : ℝ) = Real.sqrt ((7 / 5) ^ 2) by rw [Real.sqrt_sq (by norm_num)]]
      exact Real.sqrt_le_sqrt (by norm_num)
    have hd : (Real.sqrt t - Real.sqrt 2) / K ≤ 3 / 10 := by
      rw [div_le_iff₀ hK0]; nlinarith
    have : Real.sqrt t / K - Real.sqrt 2 / K = (Real.sqrt t - Real.sqrt 2) / K := by ring
    linarith
  · linarith [tail_bound_ge4 h'.le hK]

end Num
end Sec6
end Zeta5
